//! On-disk DDL for the two SQLite databases.
//!
//! The events DB (`burn.sqlite`) holds two classes of table:
//!
//! - **Derivable** — `turns`, `compactions`, `relationships`,
//!   `tool_result_events`, `user_turns`, `sessions`. Cache rebuilt by
//!   `burn state rebuild` from upstream session files.
//! - **First-party** — `stamps`, `archive_state`. Generated by the
//!   `burn stamp` verb / harness wrapper / ingest cursors. Preserved
//!   across rebuild.
//!
//! The content DB (`content.sqlite`) holds raw blobs plus an FTS5
//! virtual table, kept in sync via triggers. Lifecycle is decoupled from
//! the events DB so content prune passes don't compete with analytic
//! queries.

/// Tables that `burn state rebuild` drops + re-ingests from upstream.
pub const DERIVABLE_TABLES: &[&str] = &[
    "turns",
    "compactions",
    "relationships",
    "tool_result_events",
    "user_turns",
    "sessions",
];

/// Tables `burn state rebuild` MUST preserve byte-for-byte.
pub const FIRST_PARTY_TABLES: &[&str] = &["stamps", "archive_state"];

/// Bumped when on-disk shape changes incompatibly. Stored in
/// `archive_state.schema_version` after migration.
pub const SCHEMA_VERSION: u32 = 1;

/// DDL for `burn.sqlite`. Idempotent (`IF NOT EXISTS`) so re-applying on
/// startup is a no-op once the tables exist.
///
/// Naming: snake_case columns, plural table names, JSON columns hold
/// `record_json` so the on-disk shape stays human-debuggable until typed
/// columns land per #242 follow-ups.
pub const BURN_DDL: &str = r#"
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS turns (
    source              TEXT NOT NULL,
    session_id          TEXT NOT NULL,
    message_id          TEXT NOT NULL,
    ts                  TEXT NOT NULL,
    project             TEXT,
    project_key         TEXT,
    record_json         TEXT NOT NULL,
    content_fingerprint TEXT NOT NULL,
    PRIMARY KEY (source, session_id, message_id)
) STRICT;

CREATE INDEX IF NOT EXISTS idx_turns_content_fingerprint
    ON turns(content_fingerprint);
CREATE INDEX IF NOT EXISTS idx_turns_session
    ON turns(session_id);
CREATE INDEX IF NOT EXISTS idx_turns_ts
    ON turns(ts);

CREATE TABLE IF NOT EXISTS compactions (
    id_fingerprint TEXT PRIMARY KEY,
    source         TEXT NOT NULL,
    session_id     TEXT NOT NULL,
    ts             TEXT NOT NULL,
    record_json    TEXT NOT NULL
) STRICT;

CREATE INDEX IF NOT EXISTS idx_compactions_session
    ON compactions(session_id);

CREATE TABLE IF NOT EXISTS relationships (
    id_fingerprint     TEXT PRIMARY KEY,
    source             TEXT NOT NULL,
    session_id         TEXT NOT NULL,
    related_session_id TEXT,
    relationship_type  TEXT NOT NULL,
    ts                 TEXT,
    record_json        TEXT NOT NULL
) STRICT;

CREATE INDEX IF NOT EXISTS idx_relationships_session
    ON relationships(session_id);
CREATE INDEX IF NOT EXISTS idx_relationships_related
    ON relationships(related_session_id);

CREATE TABLE IF NOT EXISTS tool_result_events (
    id_fingerprint TEXT PRIMARY KEY,
    source         TEXT NOT NULL,
    session_id     TEXT NOT NULL,
    tool_use_id    TEXT NOT NULL,
    event_index    INTEGER NOT NULL,
    ts             TEXT,
    record_json    TEXT NOT NULL
) STRICT;

CREATE INDEX IF NOT EXISTS idx_tool_result_events_session
    ON tool_result_events(session_id);

CREATE TABLE IF NOT EXISTS user_turns (
    id_fingerprint TEXT PRIMARY KEY,
    source         TEXT NOT NULL,
    session_id     TEXT NOT NULL,
    user_uuid      TEXT NOT NULL,
    ts             TEXT NOT NULL,
    record_json    TEXT NOT NULL
) STRICT;

CREATE INDEX IF NOT EXISTS idx_user_turns_session
    ON user_turns(session_id);

CREATE TABLE IF NOT EXISTS sessions (
    source        TEXT NOT NULL,
    session_id    TEXT NOT NULL,
    first_seen_ts TEXT NOT NULL,
    last_seen_ts  TEXT NOT NULL,
    project       TEXT,
    project_key   TEXT,
    PRIMARY KEY (source, session_id)
) STRICT;

CREATE TABLE IF NOT EXISTS stamps (
    -- First-party. `written_at` (monotonic application clock) gives a
    -- deterministic order for two stamps that share the same `ts`.
    source          TEXT NOT NULL DEFAULT '',
    session_id      TEXT,
    ts              TEXT NOT NULL,
    selector_json   TEXT NOT NULL,
    enrichment_json TEXT NOT NULL,
    written_at      TEXT NOT NULL,
    PRIMARY KEY (source, session_id, ts, written_at)
);

CREATE INDEX IF NOT EXISTS idx_stamps_session ON stamps(session_id);

CREATE TABLE IF NOT EXISTS archive_state (
    -- First-party. Single-row table holding ingest cursors + last-built
    -- timestamps. Preserved across `burn state rebuild` so re-ingest
    -- doesn't have to walk every upstream file from scratch.
    id                    INTEGER PRIMARY KEY CHECK (id = 1),
    schema_version        INTEGER NOT NULL,
    upstream_cursors_json TEXT NOT NULL DEFAULT '{}',
    last_built_at         TEXT,
    last_rebuild_at       TEXT
);

INSERT INTO archive_state (id, schema_version)
    VALUES (1, 1)
    ON CONFLICT(id) DO NOTHING;
"#;

/// DDL for `content.sqlite`. The `content_fts` virtual table is wired
/// as an external-content FTS5 table over `content.body`, with sync
/// triggers on insert / delete / update so the index stays consistent
/// without callers having to remember to reindex.
pub const CONTENT_DDL: &str = r#"
CREATE TABLE IF NOT EXISTS content (
    rowid          INTEGER PRIMARY KEY,
    source         TEXT NOT NULL,
    session_id     TEXT NOT NULL,
    message_id     TEXT NOT NULL,
    content_hash   TEXT NOT NULL,
    body           TEXT NOT NULL,
    byte_length    INTEGER NOT NULL,
    created_at     TEXT NOT NULL,
    UNIQUE (session_id, message_id, content_hash)
);

CREATE INDEX IF NOT EXISTS idx_content_session ON content(session_id);
CREATE INDEX IF NOT EXISTS idx_content_created ON content(created_at);

-- External-content FTS5 over content.body so we can return ranked
-- snippets without double-storing the payload.
CREATE VIRTUAL TABLE IF NOT EXISTS content_fts USING fts5(
    body,
    content='content',
    content_rowid='rowid',
    tokenize='porter unicode61'
);

CREATE TRIGGER IF NOT EXISTS content_fts_ai AFTER INSERT ON content BEGIN
    INSERT INTO content_fts(rowid, body) VALUES (new.rowid, new.body);
END;
CREATE TRIGGER IF NOT EXISTS content_fts_ad AFTER DELETE ON content BEGIN
    INSERT INTO content_fts(content_fts, rowid, body) VALUES('delete', old.rowid, old.body);
END;
CREATE TRIGGER IF NOT EXISTS content_fts_au AFTER UPDATE ON content BEGIN
    INSERT INTO content_fts(content_fts, rowid, body) VALUES('delete', old.rowid, old.body);
    INSERT INTO content_fts(rowid, body) VALUES (new.rowid, new.body);
END;
"#;
