/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface MeasureSessionOptions {
  inputPath: string
  harness: string
  pricingPath?: string
}
/** Parse one exact session artifact and return Cloud-ready token/cost metrics. */
export declare function measureSession(opts: MeasureSessionOptions): BigIntPromoting
/**
 * Which session `analyzeSession` reads: `sessionId` (looked up in a
 * relayhistory store) or `path` (a transcript or OpenCode session file).
 */
export interface AnalyzeSessionOptions {
  harness: string
  sessionId?: string
  path?: string
  /** ai-hist database that resolves `sessionId`. */
  storeDbPath?: string
  /** Provider home searched for `sessionId`, instead of `$HOME`. */
  home?: string
  pricingPath?: string
  /** Project whose instruction files to price; defaults to the session cwd. */
  projectDir?: string
}
/** Every burn analyzer over one session; returns `burn.session-analysis.v1`. */
export declare function analyzeSession(opts: AnalyzeSessionOptions): BigIntPromoting
/**
 * Tagged error code surfaced on the thrown JS Error's `code` property.
 * Exported as a TS `string_enum` so callers can branch on
 * `e.code === BurnErrorCode.Sdk` without stringly-typed literals.
 *
 * The string values match [`SDK_ERROR_CODE`] et al. — napi-rs writes
 * them into the `code` slot via `napi_create_error`'s code argument, so
 * the round-trip from constant → JS code property is byte-identical.
 */
export const enum BurnErrorCode {
  /**
   * Catch-all for `anyhow::Error` chains the SDK raises. Refine over
   * time as the SDK's error surface grows typed variants.
   */
  Sdk = 'BURN_SDK',
  /** I/O failures from the napi boundary itself (path conversions, etc.). */
  Io = 'BURN_IO',
  /**
   * Caller passed an invalid argument shape (e.g. `since` that isn't a
   * relative range nor an ISO timestamp).
   */
  InvalidArgument = 'BURN_INVALID_ARGUMENT'
}
/**
 * Where on disk a ledger should land. Mirrors
 * `relayburn_sdk::LedgerOpenOptions`. `home` defaults to `RELAYBURN_HOME`
 * (or `~/.agentworkforce/burn`); `contentHome` overrides only the `content.sqlite`
 * path when it makes sense to park content on different storage.
 */
export interface LedgerOpenOptions {
  home?: string
  contentHome?: string
}
export interface LedgerFreshnessOptions {
  ledgerHome?: string
}
export interface LedgerFreshness {
  lastWriteAtMs?: number
  staleAfterMs: number | null
  stale: boolean
}
/**
 * Return the shared SDK staleness flag without printing. MCP and other Node
 * presenters can attach this data to their own response envelopes.
 */
export declare function ledgerFreshness(opts?: LedgerFreshnessOptions | undefined | null): Promise<LedgerFreshness>
export const enum PendingStampHarness {
  Claude = 'claude',
  Codex = 'codex',
  Opencode = 'opencode'
}
export interface WritePendingStampOptions {
  harness: PendingStampHarness
  cwd: string
  enrichment: Record<string, string>
  sessionDirHint?: string
  spawnStartTs?: string
  spawnerPid?: number
  ledgerHome?: string
}
export interface PendingStamp {
  v: number
  harness: string
  spawnerPid: number
  spawnStartTs: string
  cwd: string
  enrichment: Record<string, string>
  sessionDirHint?: string
}
export interface PendingStampWriteResult {
  file: string
  stamp: PendingStamp
}
export declare function writePendingStamp(opts: WritePendingStampOptions): PendingStampWriteResult
export interface WriteStampOptions {
  sessionId?: string
  messageId?: string
  enrichment: Record<string, string>
  /** ISO-8601 timestamp the caller observed. Defaults to "now" when omitted. */
  ts?: string
  ledgerHome?: string
}
/**
 * Write a stamp targeting an exact session id or message id. Use when the
 * launcher knows the session id up front (e.g. preallocated a Claude
 * `--session-id` UUID before spawn). Companion to `writePendingStamp`;
 * skips the sidecar manifest path entirely. At least one of `sessionId`
 * or `messageId` must be set.
 */
export declare function writeStamp(opts: WriteStampOptions): void
export interface SummaryOptions {
  session?: string
  project?: string
  /**
   * ISO timestamp (e.g. `2026-04-01T00:00:00Z`) or relative range
   * (`24h`, `7d`, `4w`, `2m`).
   */
  since?: string
  tags?: Record<string, string>
  groupByTag?: string
  ledgerHome?: string
}
export interface SummaryToolRow {
  tool: string
  tokens: bigint
  cost: number
  count: bigint
}
export interface SummaryModelRow {
  model: string
  tokens: bigint
  cost: number
}
export interface SummaryTagRow {
  tag: string
  value?: string
  tokens: bigint
  cost: number
  turnCount: bigint
}
export interface ReplacementSavingsToolRow {
  tool: string
  calls: bigint
  collapsedCalls: bigint
  estimatedTokensSaved: bigint
}
export interface ReplacementSavingsSummary {
  calls: bigint
  collapsedCalls: bigint
  estimatedTokensSaved: bigint
  byTool: Array<ReplacementSavingsToolRow>
}
export interface Summary {
  totalTokens: bigint
  totalCost: number
  turnCount: bigint
  byTool: Array<SummaryToolRow>
  byModel: Array<SummaryModelRow>
  byTag?: Array<SummaryTagRow>
  replacementSavings?: ReplacementSavingsSummary
}
export declare function summary(opts?: SummaryOptions | undefined | null): Summary
export interface SessionCostOptions {
  /** Session id to total. Omit for `{ note: 'no session id provided' }`. */
  session?: string
  ledgerHome?: string
}
export interface SessionCostResult {
  sessionId?: string
  /**
   * Total cost in USD, rounded to 6 decimal places. Surfaced as
   * `totalUSD` (screaming USD) to match the Node facade contract —
   * napi-rs would otherwise camelCase it to
   * `totalUsd`.
   */
  totalUSD: number
  totalTokens: bigint
  turnCount: bigint
  models: Array<string>
  note?: string
}
/** Compact session-scoped cost shape; powers the MCP `burn__sessionCost` tool. */
export declare function sessionCost(opts?: SessionCostOptions | undefined | null): SessionCostResult
export interface FingerprintOptions {
  /** Restrict to a single `session_id`. Mutually exclusive with `project`. */
  session?: string
  /**
   * Restrict to rows whose `project` (or normalized `project_key`)
   * matches this path string. Mutually exclusive with `session`.
   */
  project?: string
  ledgerHome?: string
}
export interface FingerprintResult {
  /** `{count}:{maxMtimeUnix}:{totalBytes}`. Compare by string equality. */
  fingerprint: string
}
export declare function fingerprint(opts?: FingerprintOptions | undefined | null): FingerprintResult
export interface TurnSpanTreeOptions {
  sessionId: string
  turnId: string
  ledgerHome?: string
}
/**
 * Per-turn span tree for one `(sessionId, turnId)` pair. Powers
 * `burn flow` / context-delta derivation. Token attributes under
 * `tokens.*` cross as `BigInt`.
 */
export declare function turnSpanTree(opts: TurnSpanTreeOptions): import('./index').TurnSpanTree
export interface SessionSpanTreesOptions {
  sessionId: string
  ledgerHome?: string
}
/**
 * Span tree for every turn in a session, in stored order. Unknown
 * session ids return an empty array.
 */
export declare function sessionSpanTrees(opts: SessionSpanTreesOptions): import('./index').TurnSpanTree[]
export interface FlowGraphOptions {
  sessionId: string
  /**
   * Cap the number of turns rendered. Omit for the SDK default (50).
   * Pass `0` to disable the cap.
   */
  maxTurns?: number
  ledgerHome?: string
}
/**
 * Per-session inference-flow DAG projected from the session's span
 * trees. Powers `burn flow`.
 */
export declare function flowGraph(opts: FlowGraphOptions): import('./index').FlowGraph
export interface ContextDeltaOptions {
  session?: string
  /**
   * Relative range (`24h`, `7d`, `4w`, `2m`). ISO timestamps are not
   * accepted — the SDK's context-delta window is a `Duration`.
   */
  since?: string
  top?: number
  minDelta?: number
  /** `'all'` (default), `'main'`, or `'subagent'`. */
  owner?: string
  ledgerHome?: string
}
/** Per-inference context-window deltas. Powers `burn overhead deltas`. */
export declare function contextDelta(opts?: ContextDeltaOptions | undefined | null): import('./index').ContextDelta[]
/**
 * Mirror of `sdk::OverheadFileKind`. Wire values match
 * The Node facade's `'claude-md' | 'agents-md'` literal union.
 */
export const enum OverheadFileKind {
  ClaudeMd = 'claude-md',
  AgentsMd = 'agents-md'
}
export interface OverheadOptions {
  /** Project path to inspect; defaults to process.cwd(). */
  project?: string
  since?: string
  kind?: OverheadFileKind
  ledgerHome?: string
}
/**
 * Per-file + per-section overhead cost attribution. Powers `burn overhead`.
 *
 * Returns the attribution result as an `OverheadResult` (see
 * `packages/sdk-node/src/index.d.ts`). Numeric u64 fields (`tokens`, `bytes`,
 * `totalLines`, `sessionCount`, `startLine`, `endLine`) cross the
 * boundary as `BigInt`; everything else is plain JS `number` / string.
 */
export declare function overhead(opts?: OverheadOptions | undefined | null): import('./index').OverheadResult
export interface OverheadTrimOptions {
  project?: string
  since?: string
  kind?: OverheadFileKind
  ledgerHome?: string
  /**
   * Recommendations per file. Default 3. Plain `u32` rather than
   * `BigInt` — `top` is a small recommendation cap, never near 2^32,
   * and the Node facade types it as `number`.
   */
  top?: number
  /** Include the unified-diff text per recommendation. Default true. */
  includeDiff?: boolean
}
/**
 * Trim recommendations for high-cost overhead-file sections. Powers
 * `burn overhead trim`. Returns an `OverheadTrimResult`-shaped JSON
 * object with the same `BigInt` substitutions as [`overhead`].
 */
export declare function overheadTrim(opts?: OverheadTrimOptions | undefined | null): import('./index').OverheadTrimResult
/**
 * Mirror of `sdk::HotspotsGroupBy`. Wire values match
 * The Node facade's
 * `'attribution' | 'bash' | 'bash-verb' | 'file' | 'subagent' |
 * 'findings'` literal union.
 */
export const enum HotspotsGroupBy {
  Attribution = 'attribution',
  Bash = 'bash',
  BashVerb = 'bash-verb',
  File = 'file',
  Subagent = 'subagent',
  Findings = 'findings'
}
export interface HotspotsOptions {
  session?: string
  project?: string
  since?: string
  groupBy?: HotspotsGroupBy
  patterns?: Array<string>
  workflow?: string
  provider?: Array<string>
  ledgerHome?: string
}
/**
 * Per-axis hotspot attribution + pattern-finding queries. Returns a
 * JSON-shaped discriminated union — see `HotspotsResult` in
 * `packages/sdk-node/src/index.d.ts`. u64 row counts (`callCount`,
 * `distinctCommands`, `ridingTurns`, `firstEmitTurnIndex`,
 * `toolCallCount`, `turnsAnalyzed`, `analyzed`, `excluded`) cross as
 * `BigInt` per the file header rule.
 */
export declare function hotspots(opts?: HotspotsOptions | undefined | null): import('./index').HotspotsResult
export interface CompareOptions {
  /** Required: at least two model names to compare. */
  models: Array<string>
  session?: string
  project?: string
  since?: string
  workflow?: string
  agent?: string
  provider?: Array<string>
  /**
   * Insufficient-sample threshold. Default 5. Plain `u32` — a turn
   * count never approaches 2^32, and TS
   * the Node facade types it as `number`.
   */
  minSample?: number
  /** One of `full`, `usage-only`, `aggregate-only`, `cost-only`, `partial`. */
  minFidelity?: string
  ledgerHome?: string
}
/**
 * Per-(model, activity) comparison shape. Returns a `CompareResult` JSON
 * object; u64 counters (`analyzedTurns`, `turns`, `pricedTurns`, fidelity
 * counts, etc.) cross as `BigInt` per the file-header rule.
 */
export declare function compare(opts: CompareOptions): import('./index').CompareResult
export interface SearchQueryOptions {
  /**
   * FTS5 query string. Supports phrase (`"out of memory"`), boolean
   * (`a OR b`), and prefix (`mem*`) syntax.
   */
  query: string
  /** Hit cap. Defaults to 25 when omitted. */
  limit?: bigint
  /** Restrict to a single session_id. Omit to search all sessions. */
  sessionId?: string
  ledgerHome?: string
}
export interface SearchHit {
  sessionId: string
  messageId: string
  source: string
  /** FTS5 BM25 rank (lower = better match). */
  rank: number
  /** `<b>…</b>`-highlighted snippet around the matching tokens. */
  snippet: string
}
export interface SearchResult {
  query: string
  hits: Array<SearchHit>
}
export declare function search(opts: SearchQueryOptions): SearchResult
export interface ExportLedgerOptions {
  ledgerHome?: string
}
export interface ExportStampsOptions {
  ledgerHome?: string
}
/**
 * Stream every event row as a JSONL-shaped JSON object. Each value has
 * the form `{ v: 1, kind: '<kind>', record: <json> }`.
 *
 * Buffered into an array for v1; matches the SDK's
 * `export_ledger() -> impl Iterator` behavior (it's already in-memory
 * today). A streaming variant is a follow-up.
 *
 * The result is wrapped in [`BigIntPromoting`] so u64 fields nested
 * inside each `record` object (`turnIndex`, `eventIndex`, `callIndex`,
 * `contentLength`, `tokensBeforeCompact`, `byteLen`, `approxTokens`,
 * `retries`, `collapsedCalls`, and the `usage` sub-object's six u64
 * keys) cross as JS `BigInt` instead of being silently truncated above
 * 2^53 by the default serde-json `number` conversion.
 */
export declare function exportLedger(opts?: ExportLedgerOptions | undefined | null): unknown[]
/**
 * Stream every stamp row as a JSONL-shaped JSON object. Sibling of
 * [`export_ledger`].
 *
 * The result is wrapped in [`BigIntPromoting`] for symmetry with
 * [`export_ledger`]. Stamps don't currently carry u64 fields, but the
 * wrapper is cheap and means a future stamp-shape change that
 * introduces one (e.g. a `byteLen` on a range bound) won't silently
 * regress to f64 truncation.
 */
export declare function exportStamps(opts?: ExportStampsOptions | undefined | null): unknown[]
/** Mirrors `packages/sdk-node/src/index.d.ts`'s `IngestOptions` shape. */
export interface IngestOptions {
  ledgerHome?: string
  /**
   * ai-hist database sessions are read from. Defaults to `$AI_HIST_DB`,
   * then the XDG data path.
   */
  storeDbPath?: string
  /** Provider home whose harness stores are read, instead of `$HOME`. */
  home?: string
}
export interface IngestReport {
  scannedSessions: bigint
  ingestedSessions: bigint
  appendedTurns: bigint
  appliedPendingStamps: bigint
}
/**
 * Sync the relayhistory store and append every session it changed since
 * the ledger's watermark. Returns a `Promise<IngestReport>`.
 *
 * The progress sink is not surfaced through the boundary.
 *
 * **Error-code contract.** Unlike the synchronous verbs (which reject
 * with `e.code` set to one of [`BurnErrorCode`]'s string values), this
 * async verb's rejection surfaces as `code: 'GenericFailure'`. The
 * rendered SDK error chain is in `e.message`. See the file header for
 * the full rationale (napi-rs 2.x's `execute_tokio_future` is
 * hard-typed to `Result<T, Error<Status>>` and `Status` is a closed
 * enum, so `'BURN_SDK'` cannot be threaded through). The
 * [`ingest_uses_generic_failure_code_runtime_invariant`] test pins
 * this discrepancy so a future napi-rs upgrade or hand-rolled deferred
 * either fixes it or has to update the test in lockstep with the
 * header docs.
 */
export declare function ingest(opts?: IngestOptions | undefined | null): Promise<IngestReport>
/**
 * Synchronously open and immediately close a ledger to validate the
 * configured paths. Returns the resolved `home` path. Mirrors the
 * `Ledger.open()` smoke-call shape from `packages/sdk-node/src/index.d.ts`; a
 * future PR can add a stateful `Ledger` JS class that holds a handle.
 */
export declare function ledgerOpen(opts?: LedgerOpenOptions | undefined | null): string
