// Generated by `napi build --dts` at publish time. This stub matches the
// expected exported function names from `crates/relayburn-sdk-node` (#247-a).
// Once the bindings land, `napi build` overwrites this file with the real
// generated declarations.
//
// The umbrella's `src/index.js` re-exports these directly. The runtime
// shape is the discriminated unions / option objects defined in
// `src/index.d.ts`; this file just declares "the binding exposes these
// names as functions."

export declare class Ledger {
  static open(opts?: { home?: string }): Promise<Ledger>;
}

export declare function ingest(opts?: unknown): Promise<unknown>;
export declare function summary(opts?: unknown): Promise<unknown>;
export declare function sessionCost(opts?: unknown): Promise<unknown>;
export declare function fingerprint(opts?: unknown): Promise<unknown>;
export declare function overhead(opts?: unknown): Promise<unknown>;
export declare function overheadTrim(opts?: unknown): Promise<unknown>;
export declare function hotspots(opts?: unknown): Promise<unknown>;
export declare function compare(opts: unknown): Promise<unknown>;
export declare function writePendingStamp(opts: unknown): unknown;
