//! `burn-sdk-node` — napi-rs bindings over `burn-sdk`.
//!
//! Compiled as a cdylib `.node` artifact and shipped as `@relayburn/sdk` on
//! npm. The TS facade in `packages/sdk-node/` is a small loader + the
//! generated `.d.ts` from this crate.
//!
//! This is a placeholder skeleton: the napi-rs deps and `#[napi]`-annotated
//! structs land in the dedicated sub-issue ("Stand up burn-sdk-node with
//! napi-rs"). The crate exists in the workspace today so the build graph,
//! versioning, and CI matrix are wired in from day one.
//!
//! Planned surface (mirrors burn-sdk):
//!
//! ```ignore
//! #[napi] pub struct Ledger { inner: burn_sdk::LedgerHandle }
//! #[napi] impl Ledger {
//!     #[napi(factory)] pub fn open(opts: Option<LedgerOptions>) -> napi::Result<Ledger>;
//!     #[napi] pub fn summary(&self, q: SummaryQuery) -> napi::Result<Summary>;
//!     #[napi] pub fn hotspots(&self, q: HotspotsQuery) -> napi::Result<Vec<HotspotFinding>>;
//! }
//! #[napi] pub async fn ingest(opts: IngestOptions) -> napi::Result<IngestReport>;
//! ```
//!
//! Binding rules:
//! - `Result<T, E>` → throws on the JS side; `E` becomes a typed `BurnError`.
//! - u64 token counts → `bigint` in TS; cost (f64 USD) → `number`.
//! - Rust `async fn` → `Promise<T>` via napi's tokio runtime integration.
//! - `.d.ts` is generated by napi-rs; never hand-edited.

#[cfg(test)]
mod tests {
    #[test]
    fn workspace_compiles() {}
}
